name: hello

on:
  push:
    branches:
      - main 

jobs:
  say-hello:
    runs-on: ubuntu-latest  

      


    steps:

      - name: Checkout do código
        uses: actions/checkout@v4


      - name: exibir mensagem
        run: echo "teceiro deploy"

      - name: Executa dockerfile
        run: docker build -t imagem .