name: hello

on:
  push:
    branches:
      - main  # O dois-pontos aqui é obrigatório

jobs:
  say-hello:
    runs-on: ubuntu-latest  # Corrigido: runs-on (com 's') e ubuntu (com 'u')
    steps:
      - name: exibir mensagem
        run: echo "Hello, Alexandre! Automação DevOps funcionando." # Faltou o comando real